# Generated by Django 4.2.27 on 2025-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(max_length=25)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_field', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
