# Generated by Django 4.2.27 on 2025-12-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_id_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=25),
        ),
    ]
