# Generated by Django 4.2.27 on 2026-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
